"""empty message

Revision ID: 424c7730ff8f
Revises: 6acfcccb330a
Create Date: 2020-07-11 21:42:54.823614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '424c7730ff8f'
down_revision = '6acfcccb330a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_details', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('order_details', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('vendor', sa.Column('phone_number', sa.String(length=13), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'phone_number')
    op.alter_column('order_details', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order_details', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
