"""empty message

Revision ID: 5f3c9d248c3d
Revises: 42a05dd5052d
Create Date: 2020-07-13 23:50:16.883217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f3c9d248c3d'
down_revision = '42a05dd5052d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_view_history',
    sa.Column('vsales_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('total_sales', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('vsales_id')
    )
    op.alter_column('order_details', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('order_details', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_details', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order_details', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_table('sales_view_history')
    # ### end Alembic commands ###
