"""empty message

Revision ID: 6acfcccb330a
Revises: d65354c88b40
Create Date: 2020-07-11 21:11:26.596201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6acfcccb330a'
down_revision = 'd65354c88b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_details', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('order_details', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('vendor', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('address', mysql.VARCHAR(length=400), nullable=False))
    op.alter_column('order_details', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order_details', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
